### ISSUE TITLE
Calculation range fail

### ISSUE THREAD

**Issue by chingyi071** [jingpu/Halide-HLS#21]
Dear all,
I tried to modify example `conv_hls`. I can pass `make pipeline_hls.cpp` but fail at `make out.png`. The error message shows
```
Error: Input buffer input is accessed at 0, which is beyond the max (-1) in dimension 2
make: *** [out.png] Aborted (core dumped)
```
However, `max(-1)` is not expected in my code. Is there anything wrong in my code?
The following is my `pipeline.cpp` and `run.cpp`, thanks

### pipeline.cpp
```cpp
#include "Halide.h"
#include <string.h>

using namespace Halide;
using std::string;

Var x("x"), y("y"), c("c");
Var xo("xo"), xi("xi"), yi("yi"), yo("yo");

class MyPipeline {
    ImageParam input;
    ImageParam weight;
    Func clamped;
    Func input_buf;
    Func output;
    Func hw_output;
    std::vector<Argument> args;

    Func convolve55_rd(Func in) {
        Func local_sum, res;
        RDom r(-1, 3, -1, 3); 

        local_sum(x, y, c) = 0;

        local_sum(x, y, c) += cast<uint16_t>(in(x+r.x, y+r.y, c)) * weight(r.x+2, r.y+2);
        res(x, y, c) = cast<uint8_t>(local_sum(x, y, c) >> 8); 

        // unroll the reduction
        local_sum.update(0).unroll(r.x).unroll(r.y);
        return res;
    }   

public:
    MyPipeline() : input(UInt(8), 3, "input"),
                   weight(UInt(8), 2, "weight"),
                   output("output"), hw_output("hw_output")
                   {
        float sigma = 1.5f;

        // define the algorithm
        clamped = BoundaryConditions::repeat_edge(input);
        input_buf(x,y,c) = clamped(x,y,c);

        hw_output = convolve55_rd(clamped);
        output(x, y, c) = cast<uint8_t>(hw_output(x, y, c));

        // constraints
        output.bound(c, 0, 3); 

        weight.dim(0).set_bounds(0, 3); 
        weight.dim(1).set_bounds(0, 3); 
        weight.dim(0).set_stride(1);
        weight.dim(1).set_stride(3);
        args.push_back(input);
        args.push_back(weight);
    }  

    void compile_cpu() {
        std::cout << "\ncompiling cpu code..." << std::endl;

        //output.print_loop_nest();
        output.compile_to_lowered_stmt("pipeline_native.ir.html", args, HTML);
        output.compile_to_header("pipeline_native.h", args, "pipeline_native");
        output.compile_to_object("pipeline_native.o", args, "pipeline_native");
    }

    void compile_gpu() {
        std::cout << "\ncompiling gpu code..." << std::endl;

        output.compute_root();

        Target target = get_target_from_environment();
        target.set_feature(Target::CUDA);
        output.compile_to_lowered_stmt("pipeline_cuda.ir.html", args, HTML, target);
        output.compile_to_header("pipeline_cuda.h", args, "pipeline_cuda", target);
        output.compile_to_object("pipeline_cuda.o", args, "pipeline_cuda", target);
    }

    void compile_hls() {
        std::cout << "\ncompiling HLS code..." << std::endl;

        clamped.compute_root(); // prepare the input for the whole image

        // HLS schedule: make a hw pipeline producing 'hw_output', taking
        // inputs of 'clamped', buffering intermediates at (output, xo) loop
        // level
        hw_output.compute_root();
        hw_output.tile(x, y, xo, yo, xi, yi, 1, 1);
        hw_output.accelerate({clamped}, x, x);  // define the inputs and the output

        Target hls_target = get_target_from_environment();
        hls_target.set_feature(Target::CPlusPlusMangling);
        output.compile_to_lowered_stmt("pipeline_hls.ir.html", args, HTML, hls_target);
        output.compile_to_hls("pipeline_hls.cpp", args, "pipeline_hls", hls_target);
        output.compile_to_header("pipeline_hls.h", args, "pipeline_hls", hls_target);
    }
};


int main(int argc, char **argv) {
    MyPipeline p1;
    p1.compile_cpu();

    MyPipeline p2;
    p2.compile_hls();

    MyPipeline p3;
    p3.compile_gpu();
    return 0;
}
```

### run.cpp
```cpp
#include <cstdio>
#include <cstdlib>
#include <cassert>
#include <math.h>

#include "pipeline_hls.h"
#include "pipeline_native.h"

#include "BufferMinimal.h"
#include "halide_image_io.h"

using Halide::Runtime::HLS::BufferMinimal;
using namespace Halide::Tools;

int main(int argc, char **argv) {
    BufferMinimal<uint8_t> input = load_image(argv[1]);
    BufferMinimal<uint8_t> weight(3,3);
//    BufferMinimal<uint8_t> input(5,5,3), weight(3,3);
    BufferMinimal<uint8_t> out_native(input.width(),input.height());
    BufferMinimal<uint8_t> out_hls(input.width(), input.height());

    printf("start.\n");

    pipeline_native(input, weight, out_native);
//    save_image(out_native, "out.png");

    printf("finish running native code\n");
    pipeline_hls(input, weight, out_native);

    printf("finish running HLS code\n");

    return 0;
}
```

**Comment by xuanyoya** [comment]
There are several issues in your code. Main reason is your tile size is 1 x 1, and window size is 3 x 3, that makes the maximum size of your image tile -1 x -1. What you should change in your code is:
1. `local_sum(x, y, c) += cast<uint16_t>(in(x+r.x, y+r.y, c)) * weight(r.x+2, r.y+2);` change to `local_sum(x, y, c) += cast<uint16_t>(in(x+r.x, y+r.y, c)) * weight(r.x+1, r.y+1);` so that the weight is accessed at the right position.
2. `hw_output.tile(x, y, xo, yo, xi, yi, 1, 1);` change to `hw_output.tile(x, y, xo, yo, xi, yi, 16, 16);`, note 16 is just an example, but you should use a number that larger than the window size.
3. `input_buf(x,y,c) = clamped(x,y,c);` get removed, since it is not used.

**Comment by chingyi071** [comment]
Thank you @xuanyoya for detail description. However, the `max(-1)` problem still occur after the modifications. Moreover, I have tried to use different size of input buffer, but it didn't change anything. Is there any other potential problem?

**Comment by xuanyoya** [comment]
@chingyi071  I didn't read your run.cpp file before. But this time, I realized you also have another error in this file. Since you are doing a convolution with window 3 x 3, so the output image size will be smaller than the input image size, you should NOT specify your output image to be:
```
    BufferMinimal<uint8_t> out_native(input.width(),input.height());
    BufferMinimal<uint8_t> out_hls(input.width(), input.height());
```

Instead, change `input.width()` and `input.height()` to some numbers that smaller than or equal to `input.width() - 2` and `input.height() - 2` .

Let me know the result. If that passes, I will close this issue.

**Comment by chingyi071** [comment]
@xuanyoya I modify it but it still fail. But the error message become `Error: Output buffer output is accessed at 2, which is beyond the max (-1) in dimension 2`. The original error message is `accessed at 0`. I'm not sure whether this phenomenon can help you

**Comment by xuanyoya** [comment]
@chingyi071  Besides, for this kind of errors, you can just try the same program and same schedule with original C backend or with original Halide repo. If you see this error occurs with the original C backend or original Halide repo, then the fastest way for you debug is to post this question on stackoverflow or Halide developer mailing list.

**Comment by xuanyoya** [comment]
Since you are doing repeat_edge as `clamped = BoundaryConditions::repeat_edge(input);`, I don't think my previous suggestion is helpful. The change you should make is 

```
    BufferMinimal<uint8_t> out_native(input.width(),input.height(), input.channels());
    BufferMinimal<uint8_t> out_hls(input.width(), input.height(), input.channels());
```

Besides, for this line `pipeline_hls(input, weight, out_native);`, it should be `pipeline_hls(input, weight, out_hls);`

**Comment by chingyi071** [comment]
The dimension of input image will be reduced from 3 to 2 in the function, so I remove `input.channels()` in output buffer declaration. I fix the input argument in `pipeline_hls()` but it still failed.

**Comment by xuanyoya** [comment]
I didn't see how you reduced the dimension from 3 to 2, and I have tried with my modification, it already passed.

**Comment by xuanyoya** [comment]
In you original code, both input and output are 3 dimensional, especially you bound the 3rd dimension of output using `output.bound(c, 0, 3)`; so please use 3 dimensions in run.cpp. If you want to reduce the 3rd dimension of input, please change 

`local_sum(x, y, c) += cast<uint16_t>(in(x+r.x, y+r.y, c)) * weight(r.x+2, r.y+2);` to
`local_sum(x, y) += cast<uint16_t>(in(x+r.x, y+r.y, r.z)) * weight(r.x+2, r.y+2);`

And also change some other code accordingly. But in that case, it is not in the scope of this issue, so the current issue will be closed.

**Comment by chingyi071** [comment]
@xuanyoya Sorry I just use reduced version of my function. This code does not reduce the dimension. And I pass the test. Thank you very much
