### ISSUE TITLE
Accelerating last function (not hw_output) not possible?

### ISSUE THREAD

**Issue by kevinkim06** [jingpu/Halide-HLS#24]
Hello,

Is it impossible to accelerate output instead of hw_output which is just in front of output like in other examples? The following code generates incorrect pipeline_hls.cpp which has syntax error "_p2_output was not declared in this scope". I'm just curious it's a bug or a un-supported feature.

#include "Halide.h"
#include <stdio.h>

using namespace Halide;

Var x,y,xo,yo,xi,yi;

class MyPipeline {
public:
    ImageParam in;
    Func in2;
    Func output;
    
    std::vector<Argument> args;

    MyPipeline() : in(UInt(8), 2)
    {
        in2(x,y) = in(x,y);
        output(x, y) =  in2(x, y) + 2 * in2(x+1, y) + 2 * in2(x+2, y) + in2(x+3, y);
        // Arguments
        args = {in};
    }

    void compile_hls() {
        std::cout << "\ncompiling HLS code..." << std::endl;

        output.tile(x, y, xo, yo, xi, yi, 480, 640);

        in2.compute_root();

        output.accelerate({in2}, xi, xo);
        // Create the target for HLS simulation
        Target hls_target = get_target_from_environment();
        hls_target.set_feature(Target::CPlusPlusMangling);
        output.compile_to_hls("pipeline_hls.cpp", args, "pipeline_hls", hls_target);
        output.compile_to_header("pipeline_hls.h", args, "pipeline_hls", hls_target);
    }
};

int main(int argc, char **argv) {
    MyPipeline p2;
    p2.compile_hls();

    return 0;
}

**Comment by xuanyoya** [comment]
It is not quite supported with the current code. As we want to make another copy (output) on the CPU side, and transfer the data (hw_output) from accelerator to that copy. This feature will be supported in the future. But no matter which function you choose to accelerate, it shouldn't affect the code you generated for the accelerator side.

**Comment by kevinkim06** [comment]
I got it. Thank you, Xuan.
