### ISSUE TITLE
Seg fault when using the packed arguments calling convention

### ISSUE THREAD

**Issue by jingpu** [jingpu/Halide-HLS#4]
After merged with release 2016/10/25, the calling convention to a HLS pipeline using the packed argument throws a seg fault in runtime.

To reproduce, uncomment the statements in the following source, and run `make` in the folder.
https://github.com/jingpu/Halide-HLS/blob/d387094996856412fe2c3b2a916b550579ce562b/apps/hls_examples/conv_hls/run.cpp#L50

**Comment by jingpu** [comment]
@jeffsetter Could you please take a look at this?

**Comment by jeffsetter** [comment]
Yea I can take a look

**Comment by jeffsetter** [comment]
I was able to fix it by using the code below. However, it appears that there is a problem now when I attempt to cast a void* that was originally a Image<uint8_t>* to a buffer_t** in pipeline_hls.cpp with the function __pipeline_hls_argv. 
However, by doing the conversion to buffer_t* first (as below), it appears to work. Do you have any suggestions on a cleaner way to do this? The code below seems a bit ugly.

    buffer_t* in_buf = in;
    buffer_t* weight_buf = weight;
    uint16_t bias = 0;
    buffer_t* out_hls_buf = out_hls;

    void** arg_values = new void*[4];
    arg_values[0] = (void*) &in_buf;
    arg_values[1] = (void*) &weight_buf;
    arg_values[2] = (void*) &bias;
    arg_values[3] = (void*) &out_hls_buf;
    pipeline_hls_argv(arg_values);
    delete [] arg_values;

**Comment by jingpu** [comment]
I find how the master branch does the _argv calling. Could you match their implementation?
https://github.com/jingpu/Halide-HLS/blob/HLS/test/generator/argvcall_aottest.cpp#L44

**Comment by jeffsetter** [comment]
I still need to cast to buffer_t* first (because my implementation uses buffer_t**), but it's a bit cleaner now.    

// cast first to buffer_t*                                                                                                                                                                                                                                          
    buffer_t* in_buf = in;
    buffer_t* weight_buf = weight;
    uint16_t bias = 0;
    buffer_t* out_hls_buf = out_hls;

    void* arg_values[4] = { &in_buf, &weight_buf, &bias, &out_hls_buf };
    pipeline_hls_argv(arg_values);

**Comment by jingpu** [comment]
Can you use buffer_t* instead of buffer_t**?

**Comment by jeffsetter** [comment]
I changed Codegen_C to use buffer_t* instead, pushed the change, and now am waiting on travis.

**Comment by jeffsetter** [comment]
Travis passed, so I'll close this.

**Comment by jingpu** [comment]
Thanks!
